# Generated by Django 3.2.6 on 2021-08-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('code', models.CharField(max_length=8, unique=True)),
                ('category', models.ManyToManyField(to='products.Category')),
            ],
        ),
    ]
